spring.application.name=terra-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/terra_db
spring.datasource.username=postgres
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=update
